providers = ["zig"]

[variables]
ZIG_VERSION = "0.15.1"
NIXPACKS_ZIG_VERSION = "0.15.1"

[phases.setup]
nixpkgsArchive = "bc725b12b2595951a3f4b112d59716d30b41001a"

[phases.build]
cmds = ["zig version", "zig build -Doptimize=ReleaseFast"]

[start]
cmd = "./zig-out/bin/ZigReflect"
